name: Auto Deploy to dev server  
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Deploy to dev server
      env:
        PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        HOST: 212.90.121.167
        USER: root
      run: |
          echo "$PRIVATE_KEY" > private_key 
          chmod 600 private_key
          ssh -i private_key   -o StrictHostKeyChecking=no  $USER@$HOST  " 
          cd /root/Doctorak-admin-angular
          pwd"
